const fs = require("fs");

const fonts = {
	vga: "./VGA-ROM.bmf"
};


console.log("Building font(s):", Object.keys(fonts).join(", "))

function runlengthEncode(bytes) {
	let prev = -1;
	let runlength = 0;
	const out = [];
	const append = () => {
		if (runlength == 0) return;
		if (runlength == 1) {
			out.push(prev)
		} else {
			out.push([prev, runlength]);
		}
		runlength = 0;
	}
	bytes.forEach(v => {
		if (v !== prev) {
			append();
			prev = v;
		}
		runlength++;
	});
	append();
	return out;
}

const exportCode = Object.entries(fonts).map(([name, filename]) => {
	const binaryData = new Uint8Array([...fs.readFileSync(filename)]);
	const rle = runlengthEncode(binaryData);
	return `export const ${name}Font = loadBmfFont(runlengthDecode(${JSON.stringify(rle)}));`;
}).join("\n");

fs.writeFileSync("src/vga-font.ts", `// ** generated by buildfonts.js ** //
import { loadBmfFont, runlengthDecode } from './bmf';	
${exportCode}
`)