const fs = require("fs");

const fonts = {
	vga: "./res/VGA-ROM.bmf",
	ega: "./res/EGA-ROM.bin",
};


console.log("Building font(s):", Object.keys(fonts).join(", "))

function runlengthEncode(bytes) {
	let prev = -1;
	let runlength = 0;
	const out = [];
	const append = () => {
		if (runlength == 0) return;
		if (runlength == 1) {
			out.push(prev)
		} else {
			out.push([prev, runlength]);
		}
		runlength = 0;
	}
	bytes.forEach(v => {
		if (v !== prev) {
			append();
			prev = v;
		}
		runlength++;
	});
	append();
	return out;
}

const exportCode = Object.entries(fonts).map(([name, filename]) => {
	const binaryData = new Uint8Array([...fs.readFileSync(filename)]);
	const rle = runlengthEncode(binaryData);
	return `export const [${name}Font8Col, ${name}Font9Col] = /*#__PURE__*/ (() => {
	const data = runlengthDecode(${JSON.stringify(rle)});
	return [loadBmfFont(data, false), loadBmfFont(data, true)];
})();`;
}).join("\n");

fs.writeFileSync("src/fonts.ts", `// ** generated by buildfonts.js ** //
import { loadBmfFont, runlengthDecode } from './bmf';	
${exportCode}
`)