const fs = require("fs");

const fonts = {
	vga: "./res/VGA-ROM.bmf",
	ega: "./res/EGA-ROM.bin",
};

console.log("Building font(s):", Object.keys(fonts).join(", "))

if (!fs.existsSync("src/fonts")) fs.mkdirSync("src/fonts");

const padHex = (n) => n.toString(16).padStart(2, "0");

function runlengthEncode(bytes) {
	let prev = 0;
	let out = "";
	let repeats = 0;

	const writeRepeats = () => {
		while (repeats > 0) {
			if (repeats == 1) {
				out += padHex(prev);
				repeats--;
			} else {
				const r = Math.min(repeats, 17);
				repeats -= r;
				out += "*" + (r-2).toString(16);
			}
		}
	}

	bytes.forEach(byte => {
		if (byte == prev) {
			repeats++;
		} else {
			writeRepeats();
			out += padHex(byte);
			prev = byte;
		}
	})
	writeRepeats();

	return out
		.replace(/[0-9a-f]/g, h => "abcdefghijklmnop"[parseInt(h, 16)])
		.replace(/([a-z])\1/g, c => c[0].toUpperCase());
}

Object.entries(fonts).forEach(([name, filename]) => {
	const binaryData = new Uint8Array([...fs.readFileSync(filename)]);
	const rle = runlengthEncode(binaryData);

	const code = `// ** generated by buildfonts.js ** //

import { loadBmfFont, runlengthDecode } from '../bmf.js';
const data = /*#__PURE__*/ runlengthDecode(${JSON.stringify(rle)});
export const _font8 = /*#__PURE__*/ loadBmfFont(data, false);
export const _font9 = /*#__PURE__*/ loadBmfFont(data, true);
`;


	fs.writeFileSync(`src/fonts/${name}.ts`, code)
});

